### ISSUE TITLE
High memory usage with docker

### ISSUE THREAD

**Issue by Uatschitchun** [airsonic/airsonic#1473]
I'm running airsonic/airsonic docker with the following docker-compose.yml:
```
version: '2'

services:
  airsonic:
    image: airsonic/airsonic
    container_name: airsonic
    restart: always
    ports:
      - 4040:4040
    expose:
      - 4040
    networks:
      - web
      - default
    volumes:
      - /home/user/docker/airsonic/data/:/airsonic/data
      - /media/mp3/:/airsonic/music
      - /media/mp3/playlists:/airsonic/playlists
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Dserver.use-forward-headers=true
      - JAVA_OPTS=-Xmx1536m
    labels:
      - "traefik.enable=true"
      - "traefik.backend=airsonic"
      - "traefik.frontend.rule=Host:airsonic.somename.somedomain.org"
      - "traefik.port=4040"
      - "traefik.docker.network=web"
      - "traefik.protocol=http"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=somename.somedomain.org"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"

networks:
  web:
    external: true
```
So far, so good. 

Problem is, it's using up over 1GB of memory!
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
9dc6c6acc860        airsonic            0.09%               1.131GiB / 7.674GiB   14.75%              183MB / 237MB       5.38GB / 1.08GB     63
```
Even on another system with only 1 album as media-source, it's up to 400MB.

Is there anything I can do to reduce the memory usage?
