### ISSUE TITLE
Unable to add managerPass to airsonic.properties crashes after install

### ISSUE THREAD

**Issue by ProfessorSalty** [airsonic/airsonic#1640]
## Problem description

I am trying to set up a stack of services in Docker that will authenticate to LDAP and, wherever possible, setting up the authentication in configuration so the user won't have to go into each app to switch it on manually. In Airsonic, it seems that I can do this by writing the necessary LDAP fields in `airsonic.properties` and volume mounting the file.  The problem is that when starting the container for first time (as in, the admin user's password has not been reset), the app crashes. Log shows an error

```
 Caused by: java.lang.IllegalStateException: managerPassword is required if managerDn is supplied
```

### Steps to reproduce

1. Write and save a `airsonic.properties` with the following content:

```
JWTKey=test
SettingsChanged=
MediaLibraryStatistics=1512 4850 62662 486912890569 15485585
LastScanned=
IndexString=A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ)
IgnoredArticles=The El La Los Las Le Les
Shortcuts=New Incoming Podcast
PlaylistFolder=/var/playlists
MusicFileTypes=mp3 ogg oga aac m4a flac wav wma aif aiff ape mpc shn
VideoFileTypes=flv avi mpg mpeg mp4 m4v mkv mov wmv ogv divx m2ts
CoverArtFileTypes2=cover.jpg cover.png cover.gif folder.jpg jpg jpeg gif png
SortAlbumsByYear=true
GettingStartedEnabled=false
WelcomeTitle=Airsonic
WelcomeSubtitle=
WelcomeMessage2=
LoginMessage=
Theme=default
LocaleLanguage=en
LocaleCountry=
LocaleVariant=
IndexCreationInterval=3
IndexCreationHour=3
FastCacheEnabled=false
OrganizeByFolderStructure=true
DownloadBitrateLimit=0
UploadBitrateLimit=0
LdapEnabled=true
LdapUrl=ldap://openldap:389/ou=people,dc=example,dc=com
LdapSearchFilter=(uid={0})
LdapManagerDn=cn=admin,dc=example,dc=com
LdapManagerPass=test
LdapAutoShadowing=false
SmtpServer=smtp.mail.net
SmtpEncryption=SSL/TLS
SmtpPort=465
SmtpUser=info@exemple.net
SmtpFrom=info@exemple.net
SmtpPassword=XXXXXXXXXXXXXXXXXXXXXXX
```

2. Write and save a `docker-compose.yml` file:'

```
version: '3.5'

services:
    openldap:
        image: osixia/openldap:1.3.0
        container_name: openldap-test
        restart: unless-stopped
        environment:
            - LDAP_RFC2307BIS_SCHEMA=true
            - LDAP_ORGANISATION=Airsonic Test
            - LDAP_DOMAIN=example.com
            - LDAP_ADMIN_PASSWORD=test
            - LDAP_CONFIG_PASSWORD=test
            - LDAP_BASE_DN=ou=people,dc=example,dc=com
            - LDAP_READONLY_USER=true
            - LDAP_READONLY_USER_USERNAME=readonly
            - LDAP_READONLY_USER_PASSWORD=readonly
            - LDAP_TLS_ENFORCE=false
        ports:
            - "389:389"
            - "636:636"
        command: --copy-service

    airsonic:
        image: airsonic/airsonic
        container_name: airsonic-test
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./airsonic.properties:/airsonic/data/airsonic.properties
        restart: unless-stopped
```

Alternatively, just clone this repo: https://github.com/ProfessorSalty/airsonic-test

## System information

 * **Airsonic version**: 10.6.0-release
 * **Operating system**: Ubuntu 19.10
 * **Java version**: Whatever is in the container
 * **Proxy server**: Traefik v2.2
 * **Client**: n/a
 * **Language**: en-us
