### ISSUE TITLE
Docker image Error: Unable to access jarfile airsonic.war

### ISSUE THREAD

**Issue by lkebin** [airsonic/airsonic#1838]
## Problem description

Docker image Error: Unable to access jarfile airsonic.war

### Steps to reproduce

Run with in Docker

## System information

Docker image latest version on Docker Hub

**Comment by ToadCast** [comment]
I'm not having this issue with the latest linked to `10.6.2-RELEASE`, you may reconsider testing again. Also it would be useful to tell which version was linked to `latest`, else it's a bit complicated to help you out.

**Comment by lkebin** [comment]
Seems the issue caused by volume settings. I was using `-v airsonic:/airsonic`

**Comment by akshat1** [comment]
> Seems the issue caused by volume settings. I was using `-v airsonic:/airsonic`

Confirming this. The following docker-compose causes this (unable to access jarfile) error:

```yml
services:
  airsonic:
    image: airsonic/airsonic
    container_name: airsonic
    restart: unless-stopped
    tty: false
    volumes:
      - /persisted/airsonic:/airsonic
      - /music:/airsonic/music
    ports:
      - 4040:4040
```

While the following configuration works:

```yml
services:
  airsonic:
    image: airsonic/airsonic
    container_name: airsonic
    restart: unless-stopped
    tty: false
    volumes:
      - /persisted/airsonic/data:/airsonic/data
      - /persisted/airsonic/playlists:/airsonic/playlists
      - /persisted/airsonic/podcasts:/airsonic/podcasts
      - /music:/airsonic/music
    ports:
      - 4040:4040
```

This bug can probably be closed (unless you intend to separate the war directory and data directories).

### Image information

REPOSITORY | TAG | IMAGE ID | CREATED | SIZE
--------------------|--------|---------------|----------------|---------
airsonic/airsonic | latest | 396b247915bb | 14 months ago | 236MB
