### ISSUE TITLE
Feature: "Smart" Playlists

### ISSUE THREAD

**Issue by calne-ca** [airsonic/airsonic#803]
It would be really cool if airsonic would support smart/dynamic playlists. With "smart" playlists I mean playlists that are not composed out of a fixed amount of songs but rather from a set of rules/filters that automatically fill the playlist with all songs that comply to these rules and filters. For example one could create a playlist that contains all songs from a set of directories:

J-Pop (smart playlist)
- /media/REOL
- /media/AKB48
- /media/YUI

This example playlist would add every song under the sub directories REOL, AKB48 and YUI and add them to the playlist.

Smart playlists have several advantages over normal playlists:
- They automatically (after every scan) add new songs to the playlists if they comply to the playlists' rules/filters 
- They automatically adapt to any filesystem change as long as it occurs under the selected directories. This includes the renaming and removal of sub directories and files.
- If you have songs/artists that you want to add to multiple playlists you do not have to adapt every single playlist every time you add a new song.

In other words: You do not need to trouble yourself with maintaining your playlists.

AIMP implemented smart playlists about 3 years ago and it is really one of its best features. I've used it for a year now and I rarely need to adapt any of my playlists.

I only mentioned the declaration of directories but of course it's also a possibility to use regex for filtering via the songs' meta data or file name.

**Comment by adamdmoss** [comment]
FYI I use beets to do something similar but more flexible - I generate smart playlists from queries and put them into playlists files which airsonic knows how to refresh.  This way I can mark files as belonging to one or more playlists explicitly, and combine these with queries based on filename, newness, samplerate, etc:

from beets/config.yaml:
```
smartplaylist:
    auto: no
    relative_to: 
    playlist_dir: /music/playlists
    playlists:
          # MANUALLY TAGGED:
        - name: g-instrumental.m3u
          query: '_playlist-instrumental:x'
        - name: g-48khz-24bit.m3u
          query: 'samplerate:48000.. bitdepth:24..'
        - name: g-48khz.m3u
          query: 'samplerate:48000..'
        - name: g-mass-effect.m3u
          query: 'mass effect'
          # MANUALLY TAGGED:
        - name: g-inoffensive-dinner.m3u
          query: '_playlist-inoffensive-dinner:x'
```
and so on.
